//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnStoreModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStoreMap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemStoreMap()
        {
            this.ItemsAvailabilities = new HashSet<ItemsAvailability>();
            this.ItemStorePriceDiscounts = new HashSet<ItemStorePriceDiscount>();
        }
    
        public int ItemStoreMapId { get; set; }
        public int ItemId { get; set; }
        public int StoreId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsAvailability> ItemsAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemStorePriceDiscount> ItemStorePriceDiscounts { get; set; }
        public virtual Store Store { get; set; }
        public virtual Item Item { get; set; }
    }
}
